### ISSUE TITLE
Add option for a hover tooltip

### ISSUE THREAD

**Issue by jdillon** [HimDek/Run-Command-Widget-for-Plasma#1]
I would love to see an option to configure a hover tool-tip for the Run command button :-)

**Comment by HimDek** [comment]
Implemented in Plasma 6 port https://github.com/HimDek/Run-Command-Widget-for-Plasma/commit/e04e8fa47faa937511176c3fd3f3a2b0c654cd6e. No more plans to update the Plasma 5 version.
